# Generated by Django 5.2.5 on 2026-02-19 05:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(blank=True, max_length=20, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=40, null=True)),
                ('idade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)])),
                ('numero', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Número inválido. Use formato brasileiro válido.', regex='^(\\+55)?[1-9]{2}9\\d{8}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
