# Generated by Django 5.2.5 on 2025-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='primeiro_nome',
            field=models.CharField(max_length=20, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(max_length=40, verbose_name='Sobrenome'),
        ),
    ]
