# Generated by Django 5.2.5 on 2026-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_perfil_primeiro_nome_alter_perfil_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
